const actionAWords = [
    {
      word: 'cry',
      translation: 'плакать',
      image: './img/actionA/cry.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'cry',
      sound: './audio/actionA/cry.mp3',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: './img/actionA/dance.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'dance',
      sound: './audio/actionA/dance.mp3',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: './img/actionA/dive.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'dive',
      sound: './audio/actionA/dive.mp3',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: './img/actionA/draw.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'draw',
      sound: './audio/actionA/draw.mp3',
    },
    {
      word: 'fish',
      translation: 'рыбачить',
      image: './img/actionA/fish.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'fish',
      sound: './audio/actionA/fish.mp3',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: './img/actionA/fly.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'fly',
      sound: './audio/actionA/fly.mp3',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: './img/actionA/hug.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'hug',
      sound: './audio/actionA/hug.mp3',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: './img/actionA/jump.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'jump',
      sound: './audio/actionA/jump.mp3',
    },
  ];
  
  const actionBWords = [
    {
      word: 'open',
      translation: 'открывать',
      image: './img/actionB/open.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'open',
      sound: './audio/actionB/open.mp3',
    },
    {
      word: 'play',
      translation: 'играть',
      image: './img/actionB/play.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'play',
      sound: './audio/actionB/play.mp3',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: './img/actionB/point.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'point',
      sound: './audio/actionB/point.mp3',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: './img/actionB/ride.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'ride',
      sound: './audio/actionB/ride.mp3',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: './img/actionB/run.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'run',
      sound: './audio/actionB/run.mp3',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: './img/actionB/sing.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'sing',
      sound: './audio/actionB/sing.mp3',
    },
    {
      word: 'skip',
      translation: 'прыгать',
      image: './img/actionB/skip.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'skip',
      sound: './audio/actionB/skip.mp3',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: './img/actionB/swim.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'swim',
      sound: './audio/actionB/swim.mp3',
    },
  ];
  
  const actionCWords = [
    {
      word: 'argue',
      translation: 'спорить',
      image: './img/actionC/argue.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'argue',
      sound: './audio/actionC/argue.mp3',
    },
    {
      word: 'build',
      translation: 'строить',
      image: './img/actionC/build.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'build',
      sound: './audio/actionC/build.mp3',
    },
    {
      word: 'carry',
      translation: 'нести',
      image: './img/actionC/carry.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'carry',
      sound: './audio/actionC/carry.mp3',
    },
    {
      word: 'catch',
      translation: 'ловить',
      image: './img/actionC/catch.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'catch',
      sound: './audio/actionC/catch.mp3',
    },
    {
      word: 'drive',
      translation: 'водить',
      image: './img/actionC/drive.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'drive',
      sound: './audio/actionC/drive.mp3',
    },
    {
      word: 'drop',
      translation: 'падать',
      image: './img/actionC/drop.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'drop',
      sound: './audio/actionC/drop.mp3',
    },
    {
      word: 'pull',
      translation: 'тянуть',
      image: './img/actionC/pull.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'pull',
      sound: './audio/actionC/pull.mp3',
    },
    {
      word: 'push',
      translation: 'толкать',
      image: './img/actionC/push.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'push',
      sound: './audio/actionC/push.mp3',
    },
  ];
  
  const adjectiveWords = [
    {
      word: 'big',
      translation: 'большой',
      image: './img/adjective/big.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'big',
      sound: './audio/adjective/big.mp3',
    },
    {
      word: 'small',
      translation: 'маленький',
      image: './img/adjective/small.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'small',
      sound: './audio/adjective/small.mp3',
    },
    {
      word: 'fast',
      translation: 'быстрый',
      image: './img/adjective/fast.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'fast',
      sound: './audio/adjective/fast.mp3',
    },
    {
      word: 'slow',
      translation: 'медленный',
      image: './img/adjective/slow.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'slow',
      sound: './audio/adjective/slow.mp3',
    },
    {
      word: 'friendly',
      translation: 'дружелюбный',
      image: './img/adjective/friendly.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'friendly',
      sound: './audio/adjective/friendly.mp3',
    },
    {
      word: 'unfriendly',
      translation: 'недружелюбный',
      image: './img/adjective/unfriendly.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'unfriendly',
      sound: './audio/adjective/unfriendly.mp3',
    },
    {
      word: 'young',
      translation: 'молодой',
      image: './img/adjective/young.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'young',
      sound: './audio/adjective/young.mp3',
    },
    {
      word: 'old',
      translation: 'старый',
      image: './img/adjective/old.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'old',
      sound: './audio/adjective/old.mp3',
    },
  ];
  
  const animalAWords = [
    {
      word: 'cat',
      translation: 'кошка',
      image: './img/animalA/cat.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'cat',
      sound: './audio/animalA/cat.mp3',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: './img/animalA/chick.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'chick',
      sound: './audio/animalA/chick.mp3',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: './img/animalA/chicken.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'chicken',
      sound: './audio/animalA/chicken.mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: './img/animalA/dog.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'dog',
      sound: './audio/animalA/dog.mp3',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: './img/animalA/horse.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'horse',
      sound: './audio/animalA/horse.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: './img/animalA/pig.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'pig',
      sound: './audio/animalA/pig.mp3',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: './img/animalA/rabbit.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'rabbit',
      sound: './audio/animalA/rabbit.mp3',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: './img/animalA/sheep.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'sheep',
      sound: './audio/animalA/sheep.mp3',
    },
  ];
  
  const animalBWords = [
    {
      word: 'bird',
      translation: 'птица',
      image: './img/animalB/bird.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'bird',
      sound: './audio/animalB/bird.mp3',
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: './img/animalB/fish1.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'fish',
      sound: './audio/animalB/fish.mp3',
    },
    {
      word: 'frog',
      translation: 'лягушка',
      image: './img/animalB/frog.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'frog',
      sound: './audio/animalB/frog.mp3',
    },
    {
      word: 'giraffe',
      translation: 'жираф',
      image: './img/animalB/giraffe.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'giraffe',
      sound: './audio/animalB/giraffe.mp3',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: './img/animalB/lion.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'lion',
      sound: './audio/animalB/lion.mp3',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: './img/animalB/mouse.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'mouse',
      sound: './audio/animalB/mouse.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: './img/animalB/turtle.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'turtle',
      sound: './audio/animalB/turtle.mp3',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: './img/animalB/dolphin.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'dolphin',
      sound: './audio/animalB/dolphin.mp3',
    },
  ];
  
  const clothesWords = [
    {
      word: 'skirt',
      translation: 'юбка',
      image: './img/clothes/skirt.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'skirt',
      sound: './audio/clothes/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'штаны',
      image: './img/clothes/pants.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'pants',
      sound: './audio/clothes/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: './img/clothes/blouse.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'blouse',
      sound: './audio/clothes/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: './img/clothes/dress.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'dress',
      sound: './audio/clothes/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинки',
      image: './img/clothes/boot.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'boot',
      sound: './audio/clothes/boot.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: './img/clothes/shirt.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'shirt',
      sound: './audio/clothes/shirt.mp3',
    },
    {
      word: 'coat',
      translation: 'платье',
      image: './img/clothes/coat.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'coat',
      sound: './audio/clothes/coat.mp3',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: './img/clothes/shoe.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'shoe',
      sound: './audio/clothes/shoe.mp3',
    },
  ];
  
  const emotionWords = [
    {
      word: 'sad',
      translation: 'грустный',
      image: './img/emotion/sad.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'sad',
      sound: './audio/emotion/sad.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: './img/emotion/angry.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'angry',
      sound: './audio/emotion/angry.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: './img/emotion/happy.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'happy',
      sound: './audio/emotion/happy.mp3',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: './img/emotion/tired.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'tired',
      sound: './audio/emotion/tired.mp3',
    },
    {
      word: 'surprised',
      translation: 'удивленный',
      image: './img/emotion/surprised.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'surprised',
      sound: './audio/emotion/surprised.mp3',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: './img/emotion/scared.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'scared',
      sound: './audio/emotion/scared.mp3',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: './img/emotion/smile.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'smile',
      sound: './audio/emotion/smile.mp3',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: './img/emotion/laugh.jpg',
      trainClicks: 0,
      correct: 0,
      mistake: 0,
      id: 'laugh',
      sound: './audio/emotion/laugh.mp3',
    },
  ];

  export {
    actionAWords,
    actionBWords,
    actionCWords,
    adjectiveWords,
    animalAWords,
    animalBWords,
    clothesWords,
    emotionWords,
  };